import{a as f,S as u,i}from"./assets/vendor-BK_rxH-O.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const d=f.create({baseURL:"https://pixabay.com/api/",headers:{},params:{key:"51716967-7d1f105da1ec22b798b2084bf",q:"",image_type:"photo",orientation:"horizontal",safesearch:"true"}});function m(e){return d.get("",{params:{q:e}}).then(o=>o.data)}const p=new u(".gallery a",{captionsData:"alt"});function g(e){const o=document.querySelector(".gallery"),s=e.map(a=>b(a)).join("");o.innerHTML=s,p.refresh()}function y(){const e=document.querySelector(".gallery");e.innerHTML=""}function h(){const e=document.querySelector(".loader");e.style.display="block"}function n(){const e=document.querySelector(".loader");e.style.display="none"}function b(e){return`<li><div class="image-box">
  <a href="${e.largeImageURL}"><img src="${e.webformatURL}" alt="${e.tags}"></a>
  <div class="image-description">
    <p class="image-stats">Downloads: ${e.downloads}</p>
    <p class="image-stats">Likes: ${e.likes}</p>
    <p class="image-stats">Views: ${e.views}</p>
    <p class="image-stats">Comments: ${e.comments}</p>
  </div>
</div></li>`}const c={form:document.querySelector(".form"),gallery:document.querySelector(".gallery")};c.form.addEventListener("submit",L);function L(e){e.preventDefault();const o=c.form.elements.searchtext.value;if(o.trim()===""){i.show({title:"Oi!",message:"Please enter a valid search option.",backgroundColor:"#fff0f6",titleColor:"#ff4d79",messageColor:"#ff80a0",progressBarColor:"#ffb3c6"}),e.target.reset();return}y(),h(),m(o).then(s=>{if(s.hits.length===0){i.show({title:"Oops!",message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#fff0f6",titleColor:"#ff4d79",messageColor:"#ff80a0",progressBarColor:"#ffb3c6"}),n(),e.target.reset();return}else g(s.hits),n()}).catch(s=>{n(),console.log(s),e.target.reset()})}
//# sourceMappingURL=index.js.map
