import{a as f,i as n,S as u}from"./assets/vendor-DDdXnYQq.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const d=f.create({baseURL:"https://pixabay.com/api/",headers:{},params:{key:"51716967-7d1f105da1ec22b798b2084bf",q:"",image_type:"photo",orientation:"horizontal",safesearch:"true"}});function m(e){return d.get("",{params:{q:e}}).then(r=>r.data)}function g(e){if(e.length<=1){i(),n.show({title:"Oops!",message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#fff0f6",titleColor:"#ff4d79",messageColor:"#ff80a0",progressBarColor:"#ffb3c6"});return}const r=document.querySelector(".gallery"),s=e.map(a=>h(a)).join("");i(),r.innerHTML=s,new u(".gallery a",{captionsData:"alt"})}function p(){const e=document.querySelector(".gallery");e.innerHTML=""}function y(){document.querySelector(".loader").classList.toggle("visible")}function i(){document.querySelector(".loader").classList.toggle("visible")}function h(e){return`<li><div class="image-box">
  <a href="${e.largeImageURL}"><img src="${e.webformatURL}" alt="${e.tags}"></a>
  <div class="image-description">
    <p class="image-stats">Downloads: ${e.downloads}</p>
    <p class="image-stats">Likes: ${e.likes}</p>
    <p class="image-stats">Views: ${e.views}</p>
    <p class="image-stats">Comments: ${e.comments}</p>
  </div>
</div></li>`}const c={form:document.querySelector(".form"),gallery:document.querySelector(".gallery")};c.form.addEventListener("submit",b);function b(e){e.preventDefault();const r=c.form.elements.searchtext.value;if(r.trim()===""){n.show({title:"Oi!",message:"Please enter a valid search option.",backgroundColor:"#fff0f6",titleColor:"#ff4d79",messageColor:"#ff80a0",progressBarColor:"#ffb3c6"}),e.target.reset();return}p(),y(),m(r).then(s=>g(s.hits)).catch(s=>console.log(s)),e.target.reset()}
//# sourceMappingURL=index.js.map
